import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  icon: {
    flex: 1,
    paddingLeft: 24,
  },
  headerTextContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerText: {
    flex: 2,
    fontSize: 16,
    lineHeight: 22,
    color: '#667080',
    fontWeight: '700',
  },
  headerSave: {
    flex: 1,
    alignItems: 'flex-end',
    paddingRight: 24,
  },
  saveText: {
    fontSize: 16,
    lineHeight: 22,
    color: '#667080',
  },
  stepsContainer: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 0.3,
  },
  activeStep: {
    backgroundColor: '#BAC0CA',
    height: 4,
    borderRadius: 4,
    width: 50,
  },
  inactiveStep: {
    opacity: 0.5,
    backgroundColor: '#BAC0CA',
    height: 4,
    borderRadius: 4,
    width: 50,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 24,
    marginTop: 30,
  },
  selectedNameContainer: {
    flexDirection: 'row',
    borderWidth: 0.3,
    paddingVertical: 5,
    paddingHorizontal: 8,
    height: 35,
    borderRadius: 6,
    alignItems: 'center',
    maxWidth: '40%',
  },
  selectedAvatar: {
    width: 24,
    height: 24,
    borderRadius: 21,
    backgroundColor: '#667080',
    marginRight: 4,
    opacity: 0.6,
  },
  selectedName: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '400',
    color: '#667080',
  },
  questionContainer: {
    marginTop: 15,
    maxWidth: '95%',
  },
  mainQuestionText: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '700',
    color: '#667080',
    // marginBottom: 24,
  },
  highlightedText: {
    color: '#A76AFF',
  },
  logDateText: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '400',
    color: '#667080',
  },

  topicContainer: {
    flex: 1,
  },
  topicPicker: {
    borderWidth: 1,
    borderColor: '#667080',
    height: 48,
    borderRadius: 6,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  topicLabel: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '400',
    color: '#667080',
    flex: 10,
  },
  noteContainer: {
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#B5E0FF',
    backgroundColor: '#FAFCFF',
    padding: 12,
    borderRadius: 4,
  },
  noteText: {
    color: '#5495EF',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
  },
  entriesContainer: {
    marginTop: 24,
    borderBottomWidth: 0.3,
  },
  answerContainer: {
    borderColor: '#667080',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 13,
    paddingVertical: 12,
    minHeight: 160,
    marginBottom: 24,
  },
  answerText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '400',
    color: '#667080',
    opacity: 0.7,
  },
});
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  icon: {
    flex: 1,
    paddingLeft: 24,
  },
  headerTextContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerText: {
    flex: 2,
    fontSize: 16,
    lineHeight: 22,
    color: '#667080',
    fontWeight: '700',
  },
  headerSave: {
    flex: 1,
    alignItems: 'flex-end',
    paddingRight: 24,
  },
  saveText: {
    fontSize: 16,
    lineHeight: 22,
    color: '#667080',
  },
  stepsContainer: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 0.3,
  },
  activeStep: {
    backgroundColor: '#BAC0CA',
    height: 4,
    borderRadius: 4,
    width: 50,
  },
  inactiveStep: {
    opacity: 0.5,
    backgroundColor: '#BAC0CA',
    height: 4,
    borderRadius: 4,
    width: 50,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 24,
    marginTop: 30,
  },
  selectedNameContainer: {
    flexDirection: 'row',
    borderWidth: 0.3,
    paddingVertical: 5,
    paddingHorizontal: 8,
    height: 35,
    borderRadius: 6,
    alignItems: 'center',
    maxWidth: '40%',
  },
  selectedAvatar: {
    width: 24,
    height: 24,
    borderRadius: 21,
    backgroundColor: '#667080',
    marginRight: 4,
    opacity: 0.6,
  },
  selectedName: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '400',
    color: '#667080',
  },
  questionContainer: {
    marginTop: 15,
    maxWidth: '95%',
  },
  mainQuestionText: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '700',
    color: '#667080',
    // marginBottom: 24,
  },
  highlightedText: {
    color: '#A76AFF',
  },
  logDateText: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '400',
    color: '#667080',
  },

  topicContainer: {
    flex: 1,
  },
  topicPicker: {
    borderWidth: 1,
    borderColor: '#667080',
    height: 48,
    borderRadius: 6,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  topicLabel: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '400',
    color: '#667080',
    flex: 10,
  },
  noteContainer: {
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#B5E0FF',
    backgroundColor: '#FAFCFF',
    padding: 12,
    borderRadius: 4,
  },
  noteText: {
    color: '#5495EF',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
  },
  entriesContainer: {
    marginTop: 24,
    borderBottomWidth: 0.3,
  },
  answerContainer: {
    borderColor: '#667080',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 13,
    paddingVertical: 12,
    minHeight: 160,
    marginBottom: 24,
  },
  answerText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '400',
    color: '#667080',
    opacity: 0.7,
  },
});
