export const asyncProgressSteps = [
  { 
    id: 1,
    title: 'Capture Feedback',
    description: 'Complete your feedback by including additional details.',
    doneDescription: 'You finished capturing feedback for ',
    inProgressDescription: 'Continue adding feedback details for ',
    date: 'Oct 20, 5:00 PM',
    done: true,
    inProgress: false,
  },
  {
    id: 2,
    title: 'Record Entries',
    description: 'You record additional entries to your feedback.',
    doneDescription: 'You completed your feedback document by recording entries.',
    inProgressDescription: 'Complete your feedback by including additional details.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  {
    id: 3,
    title: 'Review & Submit',
    description: 'You review and submit feedback entries.',
    doneDescription: 'You reviewed your feedback and sent it for submission.',
    inProgressDescription: 'Review your whole feedback and submit it for to read',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  {
    id: 6,
    title: 'Awaiting Response',
    description: ' receives your feedback.',
    doneDescription: ' viewed your feedback.',
    inProgressDescription: 'Wait for to view the feedback you sent them to know the next steps.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
    needsClarification: false,
  },
  {
    id: 7,
    title: 'Respond to Clarifications',
    description: '',
    doneDescription: 'You responded to request for clarity.',
    inProgressDescription: 'Answer to request for clarity.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
    needsClarification: false,
  },
  {
    id: 8,
    title: 'Awaiting Response',
    description: ' views your response.',
    doneDescription: ' viewed your response.',
    inProgressDescription: 'Wait for to view the response you sent.',
    done: false,
    inProgress: true,
    date: 'Oct 20, 5:00 PM',
    needsClarification: false,
  },
  {
    id: 9,
    title: 'Reflect on Discussion',
    description: 'You complete the post discussion reflection checklist.',
    doneDescription: 'You completed the post discussion reflection checklist.',
    inProgressDescription: 'Proceed to the post discussion reflection checklist.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  
];

export const faceToFaceSteps = [
  { 
    id: 1,
    title: 'Capture Feedback',
    description: 'Complete your feedback by including additional details.',
    doneDescription: 'You finished capturing feedback for ',
    inProgressDescription: 'Continue adding feedback details for ',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  {
    id: 2,
    title: 'Record Entries',
    description: 'You record additional entries to your feedback.',
    doneDescription: 'You completed your feedback document by recording entries.',
    inProgressDescription: 'Complete your feedback by including additional details.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  {
    id: 3,
    title: 'Set a 1-on-1 Discussion',
    description: 'You schedule a 1-on-1 discussion with ',
    doneDescription: 'You scheduled a 1-on-1 discussion with ',
    inProgressDescription: 'Schedule a 1-on-1 with to discuss the feedback.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  {
    id: 4,
    title: 'Review & Submit',
    description: 'You review and submit feedback entries.',
    doneDescription: 'You reviewed your feedback and sent it for submission.',
    inProgressDescription: 'Review your whole feedback and submit it for to read',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  {
    id: 6,
    title: 'Awaiting Response',
    description: 'receives your feedback.',
    doneDescription: ' viewed your feedback.',
    inProgressDescription: 'Wait for to view the feedback you sent them to know the next steps.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  {
    id: 9,
    title: '1-on-1 Discussion',
    description: 'You finish your 1-on-1 discussion with ',
    doneDescription: 'You finished your 1-on-1 discussion with ',
    inProgressDescription: 'While waiting, you can prepare for discussion by viewing your previous entries.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
  {
    id: 10,
    title: 'Reflect on Discussion',
    description: 'You complete the post discussion reflection checklist.',
    doneDescription: 'You completed the post discussion reflection checklist.',
    inProgressDescription: 'Proceed to the post discussion reflection checklist.',
    date: 'Oct 20, 5:00 PM',
    done: false,
    inProgress: true,
  },
];